-- Create cars table
create table cars (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  price_per_day decimal not null,
  status text not null,
  image_url text,
  description text,
  features jsonb,
  year integer not null,
  mileage integer not null,
  transmission text not null,
  fuel_type text not null,
  seats integer not null,
  color text not null,
  license_plate text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert mock data for cars
INSERT INTO cars (name, type, price_per_day, status, image_url, description, features, year, mileage, transmission, fuel_type, seats, color, license_plate)
VALUES
  ('Toyota Bahou', 'Sedan', 50.00, 'available', 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Comfortable sedan with great fuel economy', '["Bluetooth", "Backup Camera", "Cruise Control"]', 2023, 15000, 'Automatic', 'Gasoline', 5, 'Silver', 'ABC123'),
  ('Honda Civic', 'Sedan', 45.00, 'available', 'https://images.unsplash.com/photo-1590362891991-f776e747a588?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2116&q=80', 'Reliable and efficient compact car', '["Apple CarPlay", "Lane Departure Warning"]', 2023, 12000, 'Automatic', 'Gasoline', 5, 'Blue', 'DEF456'),
  ('Ford Mustang', 'Sports', 80.00, 'available', 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Powerful sports car with iconic design', '["Leather Seats", "Sport Suspension"]', 2023, 8000, 'Manual', 'Gasoline', 4, 'Red', 'GHI789'),
  ('Tesla Model 3', 'Electric', 90.00, 'available', 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2127&q=80', 'Modern electric vehicle with autopilot', '["Autopilot", "Premium Sound", "Glass Roof"]', 2023, 5000, 'Automatic', 'Electric', 5, 'White', 'JKL012'),
  ('BMW 3 Series', 'Luxury', 85.00, 'available', 'https://images.unsplash.com/photo-1555215695-3004980ad54e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Luxury sedan with premium features', '["Navigation", "Premium Package"]', 2023, 10000, 'Automatic', 'Gasoline', 5, 'Black', 'MNO345'),
  ('Mercedes C-Class', 'Luxury', 95.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Elegant luxury car with comfort', '["Panoramic Roof", "Premium Audio"]', 2023, 9000, 'Automatic', 'Gasoline', 5, 'Gray', 'PQR678'),
  ('Jeep Wrangler', 'SUV', 75.00, 'available', 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Adventure-ready SUV', '["4x4", "Roof Rack"]', 2023, 11000, 'Automatic', 'Diesel', 5, 'Green', 'STU901'),
  ('Toyota RAV4', 'SUV', 65.00, 'available', 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Versatile compact SUV', '["AWD", "Safety Features"]', 2023, 13000, 'Automatic', 'Hybrid', 5, 'Red', 'VWX234'),
  ('Hyundai Tucson', 'SUV', 60.00, 'available', 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Modern SUV with great features', '["Bluetooth", "Backup Camera"]', 2023, 14000, 'Automatic', 'Gasoline', 5, 'White', 'YZA567'),
  ('Kia Sportage', 'SUV', 58.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Stylish and practical SUV', '["Apple CarPlay", "Sunroof"]', 2023, 12500, 'Automatic', 'Gasoline', 5, 'Blue', 'BCD890'),
  ('Nissan Altima', 'Sedan', 48.00, 'available', 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Comfortable mid-size sedan', '["Cruise Control", "Bluetooth"]', 2023, 11500, 'Automatic', 'Gasoline', 5, 'Black', 'EFG123'),
  ('Chevrolet Malibu', 'Sedan', 46.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Reliable family sedan', '["Backup Camera", "USB Port"]', 2023, 13500, 'Automatic', 'Gasoline', 5, 'Silver', 'HIJ456'),
  ('Volkswagen Golf', 'Hatchback', 42.00, 'available', 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Fun to drive compact car', '["Manual Transmission", "Sport Mode"]', 2023, 10500, 'Manual', 'Gasoline', 5, 'White', 'KLM789'),
  ('Mazda CX-5', 'SUV', 62.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Sporty crossover SUV', '["AWD", "Premium Interior"]', 2023, 12000, 'Automatic', 'Gasoline', 5, 'Red', 'NOP012'),
  ('Subaru Outback', 'SUV', 68.00, 'available', 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Adventure-ready wagon', '["AWD", "Roof Rack"]', 2023, 9500, 'Automatic', 'Gasoline', 5, 'Green', 'QRS345'),
  ('Honda CR-V', 'SUV', 63.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Popular compact SUV', '["Honda Sensing", "Spacious Interior"]', 2023, 11000, 'Automatic', 'Hybrid', 5, 'Blue', 'TUV678'),
  ('Ford F-150', 'Truck', 85.00, 'available', 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Powerful pickup truck', '["Towing Package", "Bed Liner"]', 2023, 8500, 'Automatic', 'Gasoline', 5, 'Black', 'WXY901'),
  ('Toyota Tacoma', 'Truck', 75.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Reliable mid-size truck', '["Off-road Package", "Bed Cover"]', 2023, 7500, 'Automatic', 'Gasoline', 5, 'Gray', 'ZAB234'),
  ('Ram 1500', 'Truck', 88.00, 'available', 'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Luxury pickup truck', '["Premium Interior", "Towing Package"]', 2023, 7000, 'Automatic', 'Diesel', 5, 'Red', 'CDE567'),
  ('Chevrolet Silverado', 'Truck', 82.00, 'available', 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 'Full-size pickup truck', '["Towing Package", "Bed Liner"]', 2023, 8000, 'Automatic', 'Gasoline', 5, 'White', 'FGH890'); 